### ISSUE TITLE
Support for new Hyper-V boxes

### ISSUE THREAD

**Issue by djessich** [chef/bento#1022]
Hi,

due to Docker for Windows based on Hyper-V virtualization, it is not possible to use VirtualBox anymore, as it cannot co-exist with Hyper-V. As more and more developers use Docker, I guess Hyper-V will be used over VirtualBox (well, when using Docker for Windows there is no other opportunity anymore). However, things such as network configurations cannot be tested in Docker properly, meaning a full VM is required.

Currently only a few Hyper-V boxes are available in bento (CentOS, Ubuntu). Are there any plans to support new Hyper-V boxes? I'm very interested in Debian, Fedora, Freebsd and OpenSUSE.

Will future releases of Bento for newer versions automatically include Hyper-V boxes?

**Comment by cheeseplus** [comment]
Are there plans? Not at this time.

We've generally added platforms and providers pretty organically and in the case of Hyper-V I only implemented what worked at the time with some PRs from community members. I'm happy to investigate adding other platforms but I also don't have lots of cycles to spend figuring out platform specifics - the reason Ubuntu and CentOS made it in first was because They Just Worked (tm). I will try to add other platforms but past attempts were unproductive enough that I shelved it for a bit.

A PR is always the quickest way to get what you want added. I'm still only offering Hyper-V boxes on an experimental basis because they are built on my local machine and mostly just to see if it would work. At present there are still a several issues with adoption as one has to basically be running latest of everything (Windows 10, hyper-V, Vagrant) to get running and even then Vagrant itself has several issues still with Hyper-V. As the ecosystem matures I expect this to get easier but I want to set some expectations for how things look at present.

Will I continue to provide these boxes on a best effort basis going forward? Absolutely - but I have remote builders for all the other providers so the hyper-V builds may be delayed.
