### ISSUE TITLE
Add template for generate UEFI boxes

### ISSUE THREAD

**Issue by muellerbe** [chef/bento#1351]
### Describe the Enhancement:
Create UEFI boxes, I use the templates for building bare metal images and we use UEFI instead of legacy. The boot_command for UEFI boot is different to the legacy one. So I modify the boot_command. Adding seperate templates for this, will save time.

### Describe the Need:
all user with UEFI hardware ;) also using UEFI VMs

### Current Alternative
manually modify the templates

### Can We Help You Implement This?:
I use the templates with packer and qemu, also with vagrant and libvirt-plugin. Till now I have the boot_command for Ubuntu 20.04 and CentOS Stream 8. I need help in testing this in the rest of possible vagrant providers and operating systems and their versions. Is it worth for this project to provide UEFI templates and should I create PRs for this two templates? This could be a good base for further UEFI templates in $all operating systems.

**Comment by muellerbe** [comment]
are there any news? need more informations?

**Comment by brett-petrusek** [comment]
I am doing the same thing and would find this very helpful. Can you provide the boot commands that you are using for reference?

**Comment by Stromweld** [comment]
Please test with the lates version of the code. With the rewrite to hcl2 it is now a lot easier to add new .pkrvars.hcl files with the necessary variable overrides that are needed or you can create your own and still be able to use the templates provided. We are happy to review any PR submitted. Closing this for now due to age. Please feel free to re-open or submit a new issue/PR as needed.
