### ISSUE TITLE
source hyperv-iso doesn't work since packer v1.9.x

### ISSUE THREAD

**Issue by ThomasPatzig** [chef/bento#1509]
# Version
packer --version
1.9.1

## Environment
Win10 22H2

## Scenario
try to build a hyper-v image from win 10 ISO

## Steps to Reproduce
`packer build -force -on-error=ask PackerTemplate.pkr.hcl`

have defined HCL:
```
source "hyperv-iso" "main-windows" {
...}
build {
  sources = ["source.hyperv-iso.main-windows"]
..
}

```
## Expected Result
VM creation starts
(has worked with packer 1.8.7)

## Actual Result
```
Error: Unknown source type hyperv-iso

  on PackerTemplate.pkr.hcl line 27:
  (source code not available)

known builders: [parallels-iso azure-arm parallels-pvm azure-dtl virtualbox-ovf
vmware-iso docker amazon-instance googlecompute vsphere-iso amazon-ebsvolume
virtualbox-iso vmware-vmx amazon-chroot amazon-ebssurrogate azure-chroot
virtualbox-vm vsphere-clone file vagrant qemu null amazon-ebs]

```

**Comment by ThomasPatzig** [comment]
is there a plugin missing?

**Comment by ThomasPatzig** [comment]
I'm not sure if this is the correct area to post the issue

**Comment by ThomasPatzig** [comment]
have also opened here:
https://github.com/hashicorp/packer/issues/12468

**Comment by VishnuJin** [comment]
this is a +1 from me

**Comment by nywilken** [comment]
Just want to close the loop here. Starting with Packer 1.9.0 the community maintained components, such as hyperv-iso, were removed from the Packer binary. These external plugin components are released independently of Packer core and can be installed directly by the user. This is the recommended approach for Packer users from this point forward.

Since the chef/bento project uses HCL2 templates and has the required_plugins block I recommend running `packer init` before trying to run a Packer build.

**Comment by ThomasPatzig** [comment]
confirm

see
https://github.com/hashicorp/packer/issues/12468
for solution
