### ISSUE TITLE
Any chance we can get regular builds of arm64 targets on vmware?

### ISSUE THREAD

**Issue by drawks** [chef/bento#1518]
# Describe the Enhancement

Looking over the boxes over on vagrant cloud it looks like the arm64 builds are primarily for parallels with only a handful of vmware_desktop boxes. It'd be really great if the full matrix of platforms/distros we being serviced with the automated builds.

## Describe the Need

Support for various virtualization runtimes across the project's "official" vagrant boxes.

## Current Alternative

Build locally or run a different virtualization runtime than desired.

## Can We Help You Implement This

Any documentation or pointers as to how the build/stage process works so that I can add the additional targets.

**Comment by Stromweld** [comment]
These are ongoing. The end goal is to have stable builds for all providers. Due to the number of OS's multiplied by the providers and multiplied by the cpu archs there is a lot of builds to fix. Eventually I'll get to these but in the mean time if there is any work you can do I'd be happy to take PR's with fixes.

closing as on-going work.
