### ISSUE TITLE
Any Plan to Push Amazon Linux 2023 (al2023) to Bento Cloud?

### ISSUE THREAD

**Issue by tonyswu** [chef/bento#1534]
# Describe the Enhancement

It would be great to have Amazon Linux 2023 available from Bento Cloud.

## Describe the Need

Anyone who wish to test configuration management tools such as Chef and Ansible with Amazon Linux 2023.

## Current Alternative

I am currently using al2023 docker image to test, but it's not ideal. I haven't tried to build one myself using the bento template yet, which will be my next action item.

**Comment by Stromweld** [comment]
I would love to, but I have not found any images for VBox, VMware, parallels, qemu, hyper-v to work with. They changed the format for AMZ Linux 2 as well and so it's been a while since I've had time to refactor it's build script to get that image working again and update published to vagrant cloud. If you have any more information on where I can get sources to build the OS from I'm happy to take a look at it.

**Comment by BernhardBerbuir** [comment]
@Stromweld: Amazon Linux 2023 disk images for use with KVM and VMware can be downloaded from [cdn.amazonlinux.com](https://cdn.amazonlinux.com/al2023/os-images/latest/)

**Comment by Stromweld** [comment]
bento/amazonlinux-2023 amd64 virtualbox has been added to vagrant cloud https://app.vagrantup.com/bento/boxes/amazonlinux-2023

bento/amazonlinux-2 also got an update as well.
