### ISSUE TITLE
Use mirrors to speed-up ubuntu boxes

### ISSUE THREAD

**Issue by gionn** [chef/bento#195]
Hi,

ubuntu boxes come with the us.archive.ubuntu.com mirror configured in sources.list, however ubuntu support this nice feature: http://askubuntu.com/a/37754/17602

Can't ubuntu boxes simply use that instead of the default us mirror?

**Comment by miketheman** [comment]
Looks like #323 solves this.

**Comment by tersmitten** [comment]
Some `apt` tools do not work with `mirror://` (e.g. `cron-apt`, `apt-file`). This might be a problem.

**Comment by cheeseplus** [comment]
Unfortunately Ubuntu doesn't offer a mirror redirector so our hands are kind of tied here - closing this issue as there isn't much that can be done here with the fact mirrors.txt seems inadequate and the mirror:// URI doesn't work across the board.

Feel free to open a new one if someone finds a good holistic solution, otherwise we'll just have to deal until Canonical decides to set something up.
