### ISSUE TITLE
Upload Boxes for Parallels to Atlas

### ISSUE THREAD

**Issue by thasmo** [chef/bento#308]
The Packer templates include build configuration for the Parallels provider.

It would be nice if base boxes could be built and also provided via Atlas - for now only VirtualBox and VMware boxes have been uploaded.

**Comment by posita** [comment]
@thasmo, it's a hack (and I'm pretty sure this does not address what you're asking), but you can "trick" Vagrant into giving the illusion @rickard-von-essen's builds are part of Chef's base boxes (if naming consistency was important, but in most cases, the `override` parameter to `config.vm.provider` should make this unnecessary):

```ruby
# Vagrantfile
...
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    ...
    config.vm.provider :parallels do |v, override|
        override.vm.box = 'chef/fedora-20'
        override.vm.box_version = '0.4.0'
        override.vm.box_url = "https://atlas.hashicorp.com/rickard-von-essen/boxes/opscode_fedora-20/versions/#{override.vm.box_version}/providers/parallels.box"
        # See <https://docs.vagrantup.com/v2/vagrantfile/machine_settings.html>
    end
    ...
end
...
```

**Comment by juliandunn** [comment]
Since we at Chef don't use Parallels, we are unlikely to absorb the additional cost and workload needed to provide these boxes as a service to folks. You can regard the fact that the definitions even include Parallels clauses as merely a convenience to others like @rickard-von-essen who wish to maintain such boxes.
