### ISSUE TITLE
need to get the correct cacert.pem for AWS on CentOS boxes

### ISSUE THREAD

**Issue by jtimberman** [chef/bento#325]
On CentOS, we download the cacert.pem bundle from the curl project.

The problem with this is explained in this mailing list post: http://curl.haxx.se/mail/archive-2014-10/0062.html

This manifests itself on CentOS when using Package Cloud for yum repositories, where, on the 5.11 box, it fails because SSL can't verify the certificate. Package Cloud has a valid SSL certificate, but their repositories are backed by AWS S3, so there's a redirect that happens, and SSL verification fails.

**Comment by juliandunn** [comment]
I'm actually a little :-1: entirely on the overwriting of `cacert.pem`, so I might remove it and see what happens. I originally thought it was in order to make the cert chain work for the Vagrant insecure public key, but we're [retrieving that over plain HTTP](https://github.com/chef/bento/blob/master/packer/scripts/common/vagrant.sh#L4-L6) anyway due to CentOS 5's inability to understand SSL SNI as utilized by GitHub.

#318 also mentions this.

**Comment by jtimberman** [comment]
I'll work up a PR for testing that removes these from the various ks.cfg's.
