### ISSUE TITLE
"yum update" for RHEL/CentOS boxes

### ISSUE THREAD

**Issue by legal90** [chef/bento#425]
While Ubuntu boxes are building, all packages are automatically updated via the `update.sh` script:
https://github.com/chef/bento/blob/master/scripts/ubuntu/update.sh

What do you think about doing the similar for RHEL/CentOS boxes? Is there any strong concerns against doing `yum update`?

**Comment by legal90** [comment]
It is related to GH-406, since `yum update` can cause a distro minor version to be updated.

**Comment by cheeseplus** [comment]
So that particular script doesn't actually ""upgrade" the packages it just runs "update" which just updates the package list itself. For ubuntu the preseed.cfg actually does a 'full-upgrade' during the install process.

That said I don't see anything in the kickstart config for RHEL platforms that is doing similar. I'm certainly open to discussing adding this level of functionality.

**Comment by cheeseplus** [comment]
Related to https://github.com/chef/bento/pull/406#issuecomment-139272167 - we _don't_ want to update/upgrade the boxes to a new minor release as this is diverges with user expectations and also allows for testing the box from an 'vanilla' state for testing upgrades.

**Comment by legal90** [comment]
@cheeseplus Thanks for the explanation! I agree that we have to keep 'vanilla' state of the distribution.
I'll close this issue.
