### ISSUE TITLE
Porposal Fedora 23

### ISSUE THREAD

**Issue by aanm** [chef/bento#491]
Fedora 23 just got out, just wondering if you have any thoughts on creating a box with that fedora version.

**Comment by rickard-von-essen** [comment]
See #489

**Comment by aanm** [comment]
Thanks I'll wait then

**Comment by cheeseplus** [comment]
#489 was merged

**Comment by aanm** [comment]
@cheeseplus Where is the download link for it?

**Comment by cheeseplus** [comment]
There isn't a download link because while the definition was merged the box hasn't been pushed into the pipeline. Unfortunately I'm on the road with inconsistent internet access and the build farm requires upgrades before starting to build these. I expect to have some time coming up near the break but I'm pretty much on airplanes until Dec 18

**Comment by aanm** [comment]
@cheeseplus Ah! Okay, I thought there was a download link for it. Thanks! Once you put it online please add it as well on the README.md, thanks!

**Comment by cheeseplus** [comment]
As part of any release we update the Readme so it should be reflected there once released.

**Comment by juliandunn** [comment]
@cheeseplus I noticed that the README was updated but the Fedora 23 box can't be found on Atlas.

**Comment by cheeseplus** [comment]
@juliandunn looks like the boxes were there (well except the vmware one cause it's broken) but set to private - fixed!
