### ISSUE TITLE
Solaris 11 builds fail

### ISSUE THREAD

**Issue by fd1e4020** [chef/bento#499]
I can't build the Solaris boxes on either VirtualBox or Fusion Pro:

==> virtualbox-iso: Provisioning with shell script: scripts/common/vagrant.sh
    virtualbox-iso: mkdir: "/home/vagrant/.ssh": Operation not applicable
    virtualbox-iso: /home/vagrant/.ssh/authorized_keys: No such file or directory
    virtualbox-iso: chown: /home/vagrant/.ssh: No such file or directory
    virtualbox-iso: chmod: WARNING: can't access /home/vagrant/.ssh

Equivalent messages for Fusion.

Am I missing something obvious?

**Comment by juliandunn** [comment]
I have a wild-ass guess that [this](https://github.com/chef/bento/commit/dbc16e91f5abeaeafffa71e206a5f97a7305c1c0) commit broke the Solaris definitions because by default home directories are under `/export/home` on that platform.

The good news is I think there's a way to set these in the Solaris definition and needs some copy pasta like [this](https://github.com/chef/bento/blob/master/freebsd-9.3-i386.json#L206-L211) into it, but setting `/export/home` as the `HOME_DIR`. Want to try that and see if it works for you?

**Comment by cheeseplus** [comment]
We haven't built these in the new pipeline just yet but will be looking at this shortly.

**Comment by cheeseplus** [comment]
@scotthain I think we fixed this right?

**Comment by scotthain** [comment]
@cheeseplus yessir - I built one of the Solaris 11 boxes last week!

**Comment by cheeseplus** [comment]
Cool, closing!
