### ISSUE TITLE
What is the default password and root password ?

### ISSUE THREAD

**Issue by YangSet** [chef/bento#571]
I'm now using bento/centos-6.7 box
After SSH into my new centos, I found trouble in sudo
I've tried "vagrant", "Vagrant", "bento", "Bento", "root" and so on, but they didn't work.
Could you please tell me what the default password is?
THANKS!

**Comment by rickard-von-essen** [comment]
See https://github.com/chef/bento/blob/master/http/centos-6.7/ks.cfg#L6 and https://github.com/chef/bento/blob/master/http/centos-6.7/ks.cfg#L20

**Comment by YangSet** [comment]
THANKS... I found myself just made a stupid mistake.

**Comment by legal90** [comment]
@YangSet The default password is "vagrant" (according to [ks.cfg](https://github.com/chef/bento/blob/master/http/centos-7.2/ks.cfg#L20))

But the issue you've faced with might be caused by latter SSH daemon configuration. Do you use any provisioning systems or scripts to manage sshd configuration?
Could you reproduce this issue with this minimal Vagrantfile?

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"
end
```

**Comment by YangSet** [comment]
@legal90 The problem has been solved. I found myself was typing commands on the host machine...
Thanks a lot!
