### ISSUE TITLE
Add a 'latest' $DISTRO-$N slug on Atlas

### ISSUE THREAD

**Issue by teresaejunior** [chef/bento#662]
First of all, thank you for these boxes, they are the best I could find for Vagrant!

There is one project that I need to run on Debian Jessie, and I have noticed that Bento treats Debian point releases as if they were new versions of the operating system. Using Ubuntu as an example, there is not an _Ubuntu 16.04_ box and another _Ubuntu 16.04.1_ box (and neither there should be).

Debian point releases, just like Ubuntu point releases, include mostly security fixes, and a few bug fixes, and should never ever cause regressions (and I have never experienced one). In Debian, we generally set the version we want, and point releases are added transparently into the system.

The problem with the current approach is that whenever an official update comes out, the user has to edit the Vagrantfile manually and set the desired bento/debian-8.\* version. My recommendation would be renaming the current Debian box to just **bento/debian-8** (or alternatively bento/debian-jessie).

**Comment by cheeseplus** [comment]
The reason we keep the minor versions is that people often specifically want to try to test against what they have or test upgrade scenarios. It has been discussed making a top level slug for bento/distro-N where N is the latest and greatest at build time -  CentOS and other are in the same boat.

Our versioning as such is intentional and while we may add the slugs as mentioned, we would effectively be keeping links to the distro-N.N as other tools in the ecosystem, like test-kitchen, look and expect this.

**Comment by cheeseplus** [comment]
Renamed the issue cause if we're going to do it, we'll do it for all the platforms applicable.

**Comment by cheeseplus** [comment]
Fixed by #881

**Comment by teresaejunior** [comment]
Thank you so much for listening to my request, this is really helpful! I'm currently using bento on most of my VMs!

It just would be awesome too, if the same could be done for i386 (eg. bento/debian-8-i386).
