### ISSUE TITLE
Ubuntu boxes doubled in size from 12.04 to 16.04 

### ISSUE THREAD

**Issue by kursusHC** [chef/bento#717]
Hi and thanks for providing awesome boxes. Looking at the size of Ubuntu VB boxes : 

12.04 : 324 MB
14.04 : 513 MB
16.04 : 641 MB

What is the reason for the huge bump in size?

**Comment by tas50** [comment]
So there's certainly some things we can do to minimize the size of the images and I've done a lot of that in #718. I think you'll see some much smaller images in the next release. The images are going to grow though because the distros are growing. Even with the various new trimming methods I added in #718 here's the the numbers:

Centos 6.8: 254.5
Centos 7.2: 398.9
Ubuntu 12.04: 278.7
Ubuntu 14.04: 403.8
Ubuntu 16.04: 481.9
