### ISSUE TITLE
Ubuntu 14.04 uses US mirror by default

### ISSUE THREAD

**Issue by ravn** [chef/bento#810]
The Ubuntu 14.04 box refers to the US archive for Ubuntu.

According to https://askubuntu.com/a/104701/963 it is possible to refer to a common archive.ubuntu.com which will then resolve:

---

Open your `source.list` using your favorite text editor, ie

    sudo nano /etc/apt/sources.list

locate `http://us.archive.ubuntu.com/ubuntu` and replace it with `http://archive.ubuntu.com/ubuntu`.
---

Has this been considered?

**Comment by cheeseplus** [comment]
It's been discussed herehttps://github.com/chef/bento/issues/195 - the tl;dr is that there isn't a holistic solution that works for everyone so customizing the boxes after the fact or forking the packer templates are the recommended option.

**Comment by edmorley** [comment]
It seems that #195 discussed two different approaches:
* Using `archive.ubuntu.com` instead of `us.archive.ubuntu.com`
* Adding additional `mirror://mirrors.ubuntu.com/mirrors.txt` entries

The latter includes random third-party mirrors that from reading stack overflow seem to be less reliable, and unfortunately the discussion in #195 focused on this part, so understandably was wontfixed.

However the former maps to the more-official `<country-code>.archive.ubuntu.com` mirrors, that have seem to have stricter reliability and freshness requirements:
https://wiki.ubuntu.com/Mirrors#Country_mirror_requirements

As such, perhaps they are more viable?

Though I wonder if this is something that should be changed upstream in the Ubuntu images themselves?

**Comment by cheeseplus** [comment]
That's kinda the kicker that you mention, this should largely be fixed upstream ideally and as such there is a limited amount we the Bento team can do here. We're happy to update the templates to be more flexible but our hosted builds will almost definitely remain US centric for the time being.

**Comment by edmorley** [comment]
Hmm so digging into this more, I don't think this is really an upstream issue. The `us.archive.ubuntu.com` URLs are not hardcoded in the installer image, but automatically set by debian-installer based on the country/locale chosen for the installation:

```
# Alternatively: by default, the installer uses CC.archive.ubuntu.com where
# CC is the ISO-3166-2 code for the selected country.
```
(See: https://help.ubuntu.com/lts/installation-guide/example-preseed.txt)

So it's really this image's choice of preseed options that are causing the US mirrors to be set instead of the generic ones that will resolve to the correct location.

The mirror choice can be overridden via preseed (rather than having to edit `/etc/apt/sources.list` retrospectively), and in fact this is what's already done for the Debian images:
https://github.com/chef/bento/blob/3869bda09703774a3e5db1aca0d02c022f9d34db/http/debian-8/preseed.cfg#L10-L13

Also, as a point of reference, the official Ubuntu Docker images use `archive.ubuntu.com` too:
```
$ docker run -t --rm ubuntu:16.04 grep -Ev '^(#|$)' /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ xenial main restricted
deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ xenial universe
...
```

As such, I think it makes sense to do this - I'll open a PR.
