### ISSUE TITLE
Centos 7.4 build on vmware is missing the file provisioner that copies vmtools iso

### ISSUE THREAD

**Issue by BruceRobertson** [chef/bento#976]
The Centos 7.4 build on vmware errors when running the common/vmware.sh script to install vmware tools. vmware.sh is expecting to find a linux.iso in /home/vagrant but the file provisioner that should copy it there is missing.

In my searching I came across #747 so I'm aware that I need the vmware tools iso downloaded from vmware. The file provisioner was added in the Centos 7.3 build (see https://github.com/chef/bento/commit/292a39f432702a857e86121a0ebfdd8292f0f21b), but is now missing in the Centos 7.4 build, I'm not sure if it was removed because the intention was to rely on the open-vm-tools package

Solution:

Download latest vmtools and extract linux.iso to directory where packer is being run
Add modified file provisioner back into Centos 7.4 to run for vmware-iso builder

```JSON
"provisioners": [
    {
      "destination": "/home/vagrant/linux.iso",
      "source": "linux.iso",
      "type": "file",
        "only": [
          "vmware-iso"
       ]
    },
```

**Comment by cheeseplus** [comment]
The issue and PR you are referencing were very specific point in time fixes to work around a specific upstream bug. Packer should automatically transit the vmtool iso to the instance by because of the setting `tools_upload_flavor` https://github.com/chef/bento/blob/master/centos/centos-7.4-x86_64.json#L59 

If that's not happening or happening incorrectly, then please provide more detail of how you're determining that because the code you've added shouldn't be needed and was not needed to build out the last round of images.

**Comment by BruceRobertson** [comment]
My apologies. I'd added several remote_* options to build against an ESXi host rather than VMware Workstation. Whilst the `tools_upload_flavor` setting does look to be supported in the vmware-iso running against ESXi it clearly works in a completely different way than when running against VMware Workstation hence the iso not being found when the `common/vmware.sh` script ran.

**Comment by cheeseplus** [comment]
No problem, if we do support ESXi in the future we would need to adapt the logic but as I/we don't have a private cluster for testing/building it's always remained a nice to have. There is a pre-existing PR that might be of help (though prior to our template re-org) https://github.com/chef/bento/pull/625
